# Generated by Django 4.1.2 on 2022-10-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invigilator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('staff_id', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('joined', models.DateField()),
                ('department', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
            ],
        ),
    ]
